name: Release Please

on:
  push:
    branches: [main]

permissions: {}

env:
  NODE_VERSION: 20

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89571f0180647c42ee0ea # v4.2.0
        id: release
        with:
          release-type: node

      # Build and publish when a release is created
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        if: ${{ steps.release.outputs.release_created }}

      - name: Setup Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: npm ci

      - name: Run checks
        if: ${{ steps.release.outputs.release_created }}
        run: npm run check

      - name: Run tests
        if: ${{ steps.release.outputs.release_created }}
        run: npm test

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: npm run build
